// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

/**
 * <pre>
 * Message representing a Chambre entity
 * </pre>
 *
 * Protobuf type {@code stubs.Chambre}
 */
public  final class Chambre extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stubs.Chambre)
    ChambreOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Chambre.newBuilder() to construct.
  private Chambre(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Chambre() {
    numero_ = "";
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Chambre();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Chambre(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            numero_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 33: {

            prix_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stubs.ReservationOuterClass.internal_static_stubs_Chambre_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stubs.ReservationOuterClass.internal_static_stubs_Chambre_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stubs.Chambre.class, stubs.Chambre.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int NUMERO_FIELD_NUMBER = 2;
  private volatile java.lang.Object numero_;
  /**
   * <code>string numero = 2;</code>
   * @return The numero.
   */
  public java.lang.String getNumero() {
    java.lang.Object ref = numero_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      numero_ = s;
      return s;
    }
  }
  /**
   * <code>string numero = 2;</code>
   * @return The bytes for numero.
   */
  public com.google.protobuf.ByteString
      getNumeroBytes() {
    java.lang.Object ref = numero_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      numero_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <pre>
   * Updated to use the TypeChambre enum
   * </pre>
   *
   * <code>.stubs.TypeChambre type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Updated to use the TypeChambre enum
   * </pre>
   *
   * <code>.stubs.TypeChambre type = 3;</code>
   * @return The type.
   */
  public stubs.TypeChambre getType() {
    @SuppressWarnings("deprecation")
    stubs.TypeChambre result = stubs.TypeChambre.valueOf(type_);
    return result == null ? stubs.TypeChambre.UNRECOGNIZED : result;
  }

  public static final int PRIX_FIELD_NUMBER = 4;
  private double prix_;
  /**
   * <code>double prix = 4;</code>
   * @return The prix.
   */
  public double getPrix() {
    return prix_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNumeroBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, numero_);
    }
    if (type_ != stubs.TypeChambre.SIMPLE.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (prix_ != 0D) {
      output.writeDouble(4, prix_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNumeroBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, numero_);
    }
    if (type_ != stubs.TypeChambre.SIMPLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (prix_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, prix_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stubs.Chambre)) {
      return super.equals(obj);
    }
    stubs.Chambre other = (stubs.Chambre) obj;

    if (getId()
        != other.getId()) return false;
    if (!getNumero()
        .equals(other.getNumero())) return false;
    if (type_ != other.type_) return false;
    if (java.lang.Double.doubleToLongBits(getPrix())
        != java.lang.Double.doubleToLongBits(
            other.getPrix())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NUMERO_FIELD_NUMBER;
    hash = (53 * hash) + getNumero().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + PRIX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrix()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stubs.Chambre parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stubs.Chambre parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stubs.Chambre parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stubs.Chambre parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stubs.Chambre parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stubs.Chambre parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stubs.Chambre parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stubs.Chambre parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stubs.Chambre parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stubs.Chambre parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stubs.Chambre parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stubs.Chambre parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stubs.Chambre prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message representing a Chambre entity
   * </pre>
   *
   * Protobuf type {@code stubs.Chambre}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stubs.Chambre)
      stubs.ChambreOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stubs.ReservationOuterClass.internal_static_stubs_Chambre_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stubs.ReservationOuterClass.internal_static_stubs_Chambre_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stubs.Chambre.class, stubs.Chambre.Builder.class);
    }

    // Construct using stubs.Chambre.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      numero_ = "";

      type_ = 0;

      prix_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stubs.ReservationOuterClass.internal_static_stubs_Chambre_descriptor;
    }

    @java.lang.Override
    public stubs.Chambre getDefaultInstanceForType() {
      return stubs.Chambre.getDefaultInstance();
    }

    @java.lang.Override
    public stubs.Chambre build() {
      stubs.Chambre result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stubs.Chambre buildPartial() {
      stubs.Chambre result = new stubs.Chambre(this);
      result.id_ = id_;
      result.numero_ = numero_;
      result.type_ = type_;
      result.prix_ = prix_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stubs.Chambre) {
        return mergeFrom((stubs.Chambre)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stubs.Chambre other) {
      if (other == stubs.Chambre.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getNumero().isEmpty()) {
        numero_ = other.numero_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getPrix() != 0D) {
        setPrix(other.getPrix());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stubs.Chambre parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stubs.Chambre) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object numero_ = "";
    /**
     * <code>string numero = 2;</code>
     * @return The numero.
     */
    public java.lang.String getNumero() {
      java.lang.Object ref = numero_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numero_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string numero = 2;</code>
     * @return The bytes for numero.
     */
    public com.google.protobuf.ByteString
        getNumeroBytes() {
      java.lang.Object ref = numero_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numero_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string numero = 2;</code>
     * @param value The numero to set.
     * @return This builder for chaining.
     */
    public Builder setNumero(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      numero_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string numero = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumero() {
      
      numero_ = getDefaultInstance().getNumero();
      onChanged();
      return this;
    }
    /**
     * <code>string numero = 2;</code>
     * @param value The bytes for numero to set.
     * @return This builder for chaining.
     */
    public Builder setNumeroBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      numero_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * Updated to use the TypeChambre enum
     * </pre>
     *
     * <code>.stubs.TypeChambre type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Updated to use the TypeChambre enum
     * </pre>
     *
     * <code>.stubs.TypeChambre type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated to use the TypeChambre enum
     * </pre>
     *
     * <code>.stubs.TypeChambre type = 3;</code>
     * @return The type.
     */
    public stubs.TypeChambre getType() {
      @SuppressWarnings("deprecation")
      stubs.TypeChambre result = stubs.TypeChambre.valueOf(type_);
      return result == null ? stubs.TypeChambre.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Updated to use the TypeChambre enum
     * </pre>
     *
     * <code>.stubs.TypeChambre type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(stubs.TypeChambre value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated to use the TypeChambre enum
     * </pre>
     *
     * <code>.stubs.TypeChambre type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private double prix_ ;
    /**
     * <code>double prix = 4;</code>
     * @return The prix.
     */
    public double getPrix() {
      return prix_;
    }
    /**
     * <code>double prix = 4;</code>
     * @param value The prix to set.
     * @return This builder for chaining.
     */
    public Builder setPrix(double value) {
      
      prix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double prix = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrix() {
      
      prix_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stubs.Chambre)
  }

  // @@protoc_insertion_point(class_scope:stubs.Chambre)
  private static final stubs.Chambre DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stubs.Chambre();
  }

  public static stubs.Chambre getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Chambre>
      PARSER = new com.google.protobuf.AbstractParser<Chambre>() {
    @java.lang.Override
    public Chambre parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Chambre(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Chambre> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Chambre> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stubs.Chambre getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

