// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

public interface ChambreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stubs.Chambre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string numero = 2;</code>
   * @return The numero.
   */
  java.lang.String getNumero();
  /**
   * <code>string numero = 2;</code>
   * @return The bytes for numero.
   */
  com.google.protobuf.ByteString
      getNumeroBytes();

  /**
   * <pre>
   * Updated to use the TypeChambre enum
   * </pre>
   *
   * <code>.stubs.TypeChambre type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Updated to use the TypeChambre enum
   * </pre>
   *
   * <code>.stubs.TypeChambre type = 3;</code>
   * @return The type.
   */
  stubs.TypeChambre getType();

  /**
   * <code>double prix = 4;</code>
   * @return The prix.
   */
  double getPrix();
}
