// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stubs.Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string nom = 2;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 2;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>string prenom = 3;</code>
   * @return The prenom.
   */
  java.lang.String getPrenom();
  /**
   * <code>string prenom = 3;</code>
   * @return The bytes for prenom.
   */
  com.google.protobuf.ByteString
      getPrenomBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
