// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

public interface CreateUpdateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stubs.CreateUpdateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.stubs.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.stubs.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  stubs.Reservation getReservation();
  /**
   * <code>.stubs.Reservation reservation = 1;</code>
   */
  stubs.ReservationOrBuilder getReservationOrBuilder();
}
