// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

public interface GetAllReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stubs.GetAllReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .stubs.Reservation reservations = 1;</code>
   */
  java.util.List<stubs.Reservation> 
      getReservationsList();
  /**
   * <code>repeated .stubs.Reservation reservations = 1;</code>
   */
  stubs.Reservation getReservations(int index);
  /**
   * <code>repeated .stubs.Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .stubs.Reservation reservations = 1;</code>
   */
  java.util.List<? extends stubs.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .stubs.Reservation reservations = 1;</code>
   */
  stubs.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
