// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

public interface GetAllReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stubs.GetAllReservationRequest)
    com.google.protobuf.MessageOrBuilder {
}
