// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.example.restprojecthotel.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stubs.Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.stubs.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.stubs.Client client = 2;</code>
   * @return The client.
   */
  stubs.Client getClient();
  /**
   * <code>.stubs.Client client = 2;</code>
   */
  stubs.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>.stubs.Chambre chambre = 3;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.stubs.Chambre chambre = 3;</code>
   * @return The chambre.
   */
  stubs.Chambre getChambre();
  /**
   * <code>.stubs.Chambre chambre = 3;</code>
   */
  stubs.ChambreOrBuilder getChambreOrBuilder();

  /**
   * <code>string dateDebut = 4;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 4;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 5;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 5;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();
}
